{% set name = "cinnabar" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c2f6c4dc00e7cf0d9a0ca89e6ad7b15c99b37197dc3de82f97c05ddef3218441

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - cinnabar = cinnabar.arsenic:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - adjusttext
    - matplotlib-base
    - networkx
    - numpy
    - plotly
    - python >=3.6
    - scikit-learn
    - seaborn

test:
  imports:
    - cinnabar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/cinnabar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Consistent presentation of free energy data

extra:
  recipe-maintainers:
    - mikemhenry
    - IAlibay
    - richardjgowers
    - dwhswenson
    - RiesBen
