{% set name = "cinnabar" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 07d17fcf7037f8966c4ecbba526fa12d8cc87836556b2141feb1fb0589f778a2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - cinnabar = cinnabar.arsenic:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - adjusttext
    - matplotlib-base
    - networkx
    - numpy
    - plotly
    - python >=3.6
    - scikit-learn
    - seaborn

test:
  imports:
    - cinnabar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/cinnabar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Consistent presentation of free energy data

extra:
  recipe-maintainers:
    - mikemhenry
    - IAlibay
    - richardjgowers
    - dwhswenson
    - RiesBen
