{% set name = "cinnabar" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - cinnabar = cinnabar.arsenic:main

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - adjusttext
    - matplotlib-base
    - networkx
    - numpy
    - plotly
    - python >=3.8
    - scikit-learn
    - seaborn

test:
  imports:
    - cinnabar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/cinnabar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Consistent presentation of free energy data

extra:
  recipe-maintainers:
    - mikemhenry
    - IAlibay
    - richardjgowers
    - dwhswenson
    - RiesBen
