{% set python_min = '3.10' %}
{% set name = "cinnabar" %}
{% set version = "0.5.0rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: 37cbc2b2bc7acdb0184ead8ad63bf51e83dd2191
  git_depth: -1

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - cinnabar = cinnabar.arsenic:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - adjusttext
    - matplotlib-base
    - networkx
    - numpy
    - openff-units
    - plotly
    - python >={{ python_min }}
    - scikit-learn
    - seaborn

test:
  imports:
    - cinnabar
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest --pyargs cinnabar

about:
  home: https://github.com/OpenFreeEnergy/cinnabar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Consistent presentation of free energy data

extra:
  recipe-maintainers:
    - mikemhenry
    - IAlibay
    - dwhswenson
    - RiesBen
    - atravitz
