{% set name = "cinnabar" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7398248526f89049eff94f9ded50860a8650cdb4b1b031efed0157225210737c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - cinnabar = cinnabar.arsenic:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - adjusttext
    - matplotlib-base
    - networkx
    - numpy
    - plotly
    - python >=3.6
    - scikit-learn
    - seaborn

test:
  imports:
    - cinnabar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/cinnabar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Consistent presentation of free energy data

extra:
  recipe-maintainers:
    - mikemhenry
    - IAlibay
    - richardjgowers
    - dwhswenson
    - RiesBen
